## For more information about this file, see: 
## https://github.com/sestaton/tephra/wiki/Specifications-and-example-usage.
all:
  - logfile:          tephra_tair10_full.log
  - genome:           TAIR10_chr1-5.fas
  - outfile:          TAIR10_chr1-5_tephra_transposons.gff3
  - repeatdb:         repbase1801_athaliana.fasta 
  - trnadb:           TephraDB
  - hmmdb:            TephraDB
  - threads:          24
  - clean:            YES
  - debug:            NO
  - subs_rate:        1e-8
findltrs:
  - dedup:             NO
  - tnpfilter:         NO
  - domains_requred:   NO
    ltrharvest:
      - mintsd:         4
      - maxtsd:         20
      - minlenltr:      100
      - maxlenltr:      1000
      - mindistltr:     1000
      - maxdistltr:     15000
      - seedlength:     30
      - tsdradius:      60
      - xdrop:          5
      - swmat:          2 
      - swmis:          -2
      - swins:          -3
      - swdel:          -3
      - overlaps:       best
    ltrdigest:
      - pptradius:      30
      - pptlen:         8 30
      - pptagpr:        0.25
      - uboxlen:        3 30
      - uboxutpr:       0.91
      - pbsradius:      30
      - pbslen:         11 30
      - pbsoffset:      0 5
      - pbstrnaoffset:  0 5
      - pbsmaxeditdist: 1
      - pdomevalue:     1E-6
      - pdomcutoff:     NONE
      - maxgaplen:      50
classifyltrs:
  - percentcov:       50
  - percentid:        80
  - hitlen:           80
illrecomb:
  - repeat_pid:       10
ltrage:
  - all:              NO
maskref:
  - percentid:        80
  - hitlength:        70
  - splitsize:        5000000
  - overlap:          100
sololtr:
  - percentid:        39
  - percentcov:       80
  - matchlen:         80
  - numfamilies:      20
  - allfamilies:      NO
tirage:
  - all:              NO
