all:
  - logfile:          t/test_data/ref_tephra_findltrs.log
  - genome:           t/test_data/ref.fas
  - outfile:          t/test_data/tephra_transposons.gff3
  - repeatdb:         t/test_data/repdb.fas 
  - trnadb:           TephraDB
  - hmmdb:            TephraDB
  - threads:          2
  - clean:            YES
  - debug:            NO
  - subs_rate:        1e-8
findltrs:
  - dedup:            NO
  - tnpfilter:        NO
  - domains_required: NO
  - ltrharvest:
    - mintsd: 4
    - maxtsd: 6
    - minlenltr: 100
    - maxlenltr: 6000
    - mindistltr: 1500
    - maxdistltr: 25000
    - seedlength: 30
    - tsdradius: 60
    - xdrop: 5
    - swmat: 2 
    - swmis: -2
    - swins: -3
    - swdel: -3
    - overlaps: best
  - ltrdigest:
    - pptradius: 30
    - pptlen: 8 30
    - pptagpr: 0.25
    - uboxlen: 3 30
    - uboxutpr: 0.91
    - pbsradius: 30
    - pbslen: 11 30
    - pbsoffset: 0 5
    - pbstrnaoffset: 0 5
    - pbsmaxeditdist: 1
    - pdomevalue: 10E-6
    - pdomcutoff: NONE
    - maxgaplen: 50
classifyltrs:
  - percentcov:       50
  - percentid:        80
  - hitlen:           80
illrecomb:
  - repeat_pid:       10
ltrage:
  - all:              NO
maskref:
  - percentid:        80
  - hitlength:        70
  - splitsize:        5000000
  - overlap:          100
sololtr:
  - percentid:        39
  - percentcov:       80
  - matchlen:         80
  - numfamilies:      20
  - allfamilies:      NO
tirage:
  - all:              NO
